### ISSUE TITLE
Apollo playground

### ISSUE THREAD

**Issue by yacosta738** [newbeea/nuxt3-apollo-starter#1]
How can I work with the ApolloServerPluginLandingPageGraphQLPlayground in this project?

**Comment by newbeea** [comment]
> 

ApolloServerPluginLandingPageGraphQLPlayground can't be used directly, I added a [handler](https://github.com/newbeea/nuxt3-apollo-starter/blob/master/server/api/playground.ts) in the server directory.  
Now you could pull the new code, yarn, then visit http://localhost:3000/api/playground.

**Comment by yacosta738** [comment]
Thank you

**Comment by newbeea** [comment]
> Thank you

Glad that helped
