### ISSUE TITLE
Failed to resolve import "@vue/apollo-composable"

### ISSUE THREAD

**Issue by cheungchingli** [newbeea/nuxt3-apollo-starter#3]
Failed to resolve import "@vue/apollo-composable" from "virtual:/.nuxt/dist.plugin.d43e34b4.mjs". Does the file exist?

**Comment by newbeea** [comment]
> Failed to resolve import "@vue/apollo-composable" from "virtual:/.nuxt/dist.plugin.d43e34b4.mjs". Does the file exist?

你是如何使用的呢

clone > yarn > yarn dev 这种顺序我又测了一遍，没发现这个错误

pnpm 这种生产模式会有各种各样的问题

**Comment by cheungchingli** [comment]
我是和element-plus一起使用的，可能是因为版本不兼容？没有安装成功？

**Comment by newbeea** [comment]
> 我是和element-plus一起使用的，可能是因为版本不兼容？没有安装成功？
element-plus 的话加到 transpile 里了么，试了element-plus没有这个报错
```
  build: {
    transpile: ['graphql', 'element-plus'],
  },
```
是yarn么，什么版本，nuxt3  和 npm、pnpm 都兼容不太好

**Comment by cheungchingli** [comment]
用yarn可以了，感恩。请问怎么实现订阅更新数据呢？（在setup里面）好像没有apollo对象。

**Comment by cheungchingli** [comment]
> > 我是和element-plus一起使用的，可能是因为版本不兼容？没有安装成功？
> 
> element-plus 的话加到 transpile 里了么，试了element-plus没有这个报错
> 
> ```
>   build: {
>     transpile: ['graphql', 'element-plus'],
>   },
> ```
> 
> 是yarn么，什么版本，nuxt3 和 npm、pnpm 都兼容不太好

加了会报错的。

**Comment by newbeea** [comment]
> 用yarn可以了，感恩。请问怎么实现订阅更新数据呢？（在setup里面）好像没有apollo对象。

有 client, 例子 [Home.vue](https://github.com/newbeea/nuxt3-apollo-starter/blob/master/components/Home.vue)

// use clients directly $apollo.default  $apollo.trevorblades
// const { $apollo } = useNuxtApp()
