### ISSUE TITLE
SSR not work.

### ISSUE THREAD

**Issue by shtse8** [newbeea/nuxt3-apollo-starter#4]
Thanks for your starter. I can add graphql to my nuxt3 project.
Everything works fine, but not SSR.
even `prefetch` set to `true`, nothing is returned in SSR.
Do you have any idea?

**Comment by shtse8** [comment]
It turns out I am using relative path in config.

**Comment by Pysdbi** [comment]
I have the same problem, but I don't understand why. The request is invoked on the server, but the page does not wait for the request to complete. How to make data both loaded and rendered in ssr? @newbeea
